-- ============================================================
-- Mini BOP - Fase 1
-- Script 02 - Core Tables
-- Execute conectado como MINI_BOP.
-- ============================================================

ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD';

CREATE TABLE currency (
    currency_code      VARCHAR2(3)    CONSTRAINT pk_currency PRIMARY KEY,
    currency_name      VARCHAR2(100)  NOT NULL,
    is_active          CHAR(1)        DEFAULT 'Y' NOT NULL,
    created_at         TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT ck_currency_active CHECK (is_active IN ('Y','N'))
);

CREATE TABLE book (
    book_id            NUMBER GENERATED BY DEFAULT AS IDENTITY,
    book_code          VARCHAR2(30)   NOT NULL,
    book_name          VARCHAR2(100)  NOT NULL,
    desk_name          VARCHAR2(100),
    region_code        VARCHAR2(10),
    is_active          CHAR(1)        DEFAULT 'Y' NOT NULL,
    created_at         TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_book PRIMARY KEY (book_id),
    CONSTRAINT uk_book_code UNIQUE (book_code),
    CONSTRAINT ck_book_active CHECK (is_active IN ('Y','N'))
);

CREATE TABLE portfolio (
    portfolio_id       NUMBER GENERATED BY DEFAULT AS IDENTITY,
    portfolio_code     VARCHAR2(30)   NOT NULL,
    portfolio_name     VARCHAR2(100)  NOT NULL,
    book_id            NUMBER         NOT NULL,
    is_active          CHAR(1)        DEFAULT 'Y' NOT NULL,
    created_at         TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_portfolio PRIMARY KEY (portfolio_id),
    CONSTRAINT uk_portfolio_code UNIQUE (portfolio_code),
    CONSTRAINT fk_portfolio_book FOREIGN KEY (book_id) REFERENCES book(book_id),
    CONSTRAINT ck_portfolio_active CHECK (is_active IN ('Y','N'))
);

CREATE TABLE counterparty (
    counterparty_id    NUMBER GENERATED BY DEFAULT AS IDENTITY,
    counterparty_code  VARCHAR2(30)   NOT NULL,
    counterparty_name  VARCHAR2(150)  NOT NULL,
    country_code       VARCHAR2(2),
    sector             VARCHAR2(50),
    rating             VARCHAR2(10),
    is_active          CHAR(1)        DEFAULT 'Y' NOT NULL,
    created_at         TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_counterparty PRIMARY KEY (counterparty_id),
    CONSTRAINT uk_counterparty_code UNIQUE (counterparty_code),
    CONSTRAINT ck_counterparty_active CHECK (is_active IN ('Y','N'))
);

CREATE TABLE instrument (
    instrument_id      NUMBER GENERATED BY DEFAULT AS IDENTITY,
    instrument_code    VARCHAR2(50)   NOT NULL,
    isin               VARCHAR2(12),
    instrument_name    VARCHAR2(150)  NOT NULL,
    asset_class        VARCHAR2(30)   NOT NULL,
    product_type       VARCHAR2(30)   NOT NULL,
    currency_code      VARCHAR2(3)    NOT NULL,
    maturity_date      DATE,
    issuer_name        VARCHAR2(150),
    is_active          CHAR(1)        DEFAULT 'Y' NOT NULL,
    created_at         TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_instrument PRIMARY KEY (instrument_id),
    CONSTRAINT uk_instrument_code UNIQUE (instrument_code),
    CONSTRAINT fk_instrument_currency FOREIGN KEY (currency_code) REFERENCES currency(currency_code),
    CONSTRAINT ck_instrument_asset CHECK (asset_class IN ('EQUITY','FIXED_INCOME','FX','MONEY_MARKET','DERIVATIVE')),
    CONSTRAINT ck_instrument_active CHECK (is_active IN ('Y','N'))
);

CREATE TABLE fx_rate (
    rate_date          DATE           NOT NULL,
    from_currency      VARCHAR2(3)    NOT NULL,
    to_currency        VARCHAR2(3)    NOT NULL,
    rate               NUMBER(18,8)   NOT NULL,
    created_at         TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_fx_rate PRIMARY KEY (rate_date, from_currency, to_currency),
    CONSTRAINT fk_fx_from_currency FOREIGN KEY (from_currency) REFERENCES currency(currency_code),
    CONSTRAINT fk_fx_to_currency FOREIGN KEY (to_currency) REFERENCES currency(currency_code),
    CONSTRAINT ck_fx_rate_positive CHECK (rate > 0)
);

CREATE TABLE market_price (
    price_date         DATE           NOT NULL,
    instrument_id      NUMBER         NOT NULL,
    price              NUMBER(18,6)   NOT NULL,
    price_currency     VARCHAR2(3)    NOT NULL,
    source_system      VARCHAR2(30)   DEFAULT 'MANUAL' NOT NULL,
    created_at         TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_market_price PRIMARY KEY (price_date, instrument_id),
    CONSTRAINT fk_mp_instrument FOREIGN KEY (instrument_id) REFERENCES instrument(instrument_id),
    CONSTRAINT fk_mp_currency FOREIGN KEY (price_currency) REFERENCES currency(currency_code),
    CONSTRAINT ck_market_price_positive CHECK (price > 0)
);

CREATE TABLE trade (
    trade_id           NUMBER GENERATED BY DEFAULT AS IDENTITY,
    external_trade_id  VARCHAR2(50)   NOT NULL,
    source_system      VARCHAR2(30)   NOT NULL,
    trade_date         DATE           NOT NULL,
    settlement_date    DATE,
    portfolio_id       NUMBER         NOT NULL,
    book_id            NUMBER         NOT NULL,
    counterparty_id    NUMBER         NOT NULL,
    instrument_id      NUMBER         NOT NULL,
    buy_sell           CHAR(1)        NOT NULL,
    quantity           NUMBER(18,4)   NOT NULL,
    trade_price        NUMBER(18,6)   NOT NULL,
    trade_currency     VARCHAR2(3)    NOT NULL,
    notional_amount    NUMBER(20,4),
    market_value       NUMBER(20,4),
    amount_eur         NUMBER(20,4),
    trade_status       VARCHAR2(20)   DEFAULT 'NEW' NOT NULL,
    created_at         TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at         TIMESTAMP,
    CONSTRAINT pk_trade PRIMARY KEY (trade_id),
    CONSTRAINT uk_trade_external UNIQUE (external_trade_id, source_system),
    CONSTRAINT fk_trade_portfolio FOREIGN KEY (portfolio_id) REFERENCES portfolio(portfolio_id),
    CONSTRAINT fk_trade_book FOREIGN KEY (book_id) REFERENCES book(book_id),
    CONSTRAINT fk_trade_counterparty FOREIGN KEY (counterparty_id) REFERENCES counterparty(counterparty_id),
    CONSTRAINT fk_trade_instrument FOREIGN KEY (instrument_id) REFERENCES instrument(instrument_id),
    CONSTRAINT fk_trade_currency FOREIGN KEY (trade_currency) REFERENCES currency(currency_code),
    CONSTRAINT ck_trade_side CHECK (buy_sell IN ('B','S')),
    CONSTRAINT ck_trade_qty CHECK (quantity > 0),
    CONSTRAINT ck_trade_price CHECK (trade_price > 0),
    CONSTRAINT ck_trade_status CHECK (trade_status IN ('NEW','VALIDATED','PROCESSED','REJECTED','CANCELLED'))
);

CREATE TABLE trade_event (
    trade_event_id     NUMBER GENERATED BY DEFAULT AS IDENTITY,
    trade_id           NUMBER         NOT NULL,
    event_type         VARCHAR2(30)   NOT NULL,
    event_status       VARCHAR2(20)   NOT NULL,
    event_message      VARCHAR2(4000),
    created_at         TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_trade_event PRIMARY KEY (trade_event_id),
    CONSTRAINT fk_trade_event_trade FOREIGN KEY (trade_id) REFERENCES trade(trade_id),
    CONSTRAINT ck_trade_event_type CHECK (event_type IN ('CAPTURE','VALIDATION','ENRICHMENT','PROCESSING','EXPORT','RECONCILIATION')),
    CONSTRAINT ck_trade_event_status CHECK (event_status IN ('SUCCESS','WARNING','ERROR'))
);

PROMPT Core tables created successfully.
