-- ============================================================
-- Mini BOP - Fase 1
-- Script 03 - Staging Tables
-- Execute conectado como MINI_BOP.
-- ============================================================

CREATE TABLE stg_trade_raw (
    stg_trade_id        NUMBER GENERATED BY DEFAULT AS IDENTITY,
    batch_id            NUMBER,
    external_trade_id   VARCHAR2(50),
    source_system       VARCHAR2(30),
    trade_date_txt      VARCHAR2(20),
    settlement_date_txt VARCHAR2(20),
    book_code           VARCHAR2(30),
    portfolio_code      VARCHAR2(30),
    counterparty_code   VARCHAR2(30),
    instrument_code     VARCHAR2(50),
    buy_sell            VARCHAR2(10),
    quantity_txt        VARCHAR2(50),
    trade_price_txt     VARCHAR2(50),
    trade_currency      VARCHAR2(3),
    raw_payload         CLOB,
    processing_status   VARCHAR2(20) DEFAULT 'NEW' NOT NULL,
    error_count         NUMBER DEFAULT 0 NOT NULL,
    created_at          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    processed_at        TIMESTAMP,
    CONSTRAINT pk_stg_trade_raw PRIMARY KEY (stg_trade_id),
    CONSTRAINT ck_stg_trade_status CHECK (processing_status IN ('NEW','VALIDATED','PROCESSED','REJECTED'))
);

CREATE TABLE stg_trade_error (
    stg_error_id        NUMBER GENERATED BY DEFAULT AS IDENTITY,
    stg_trade_id        NUMBER NOT NULL,
    batch_id            NUMBER,
    error_code          VARCHAR2(50) NOT NULL,
    error_message       VARCHAR2(1000) NOT NULL,
    error_severity      VARCHAR2(20) DEFAULT 'ERROR' NOT NULL,
    column_name         VARCHAR2(100),
    created_at          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_stg_trade_error PRIMARY KEY (stg_error_id),
    CONSTRAINT fk_stg_error_trade FOREIGN KEY (stg_trade_id) REFERENCES stg_trade_raw(stg_trade_id),
    CONSTRAINT ck_stg_error_severity CHECK (error_severity IN ('INFO','WARNING','ERROR','FATAL'))
);

PROMPT Staging tables created successfully.
