-- ============================================================
-- Mini BOP - Fase 1
-- Script 04 - Batch and Log Tables
-- Execute conectado como MINI_BOP.
-- ============================================================

CREATE TABLE etl_batch (
    batch_id            NUMBER GENERATED BY DEFAULT AS IDENTITY,
    batch_name          VARCHAR2(100) NOT NULL,
    source_system       VARCHAR2(30),
    file_name           VARCHAR2(255),
    status              VARCHAR2(20) DEFAULT 'RUNNING' NOT NULL,
    started_at          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    ended_at            TIMESTAMP,
    total_rows          NUMBER DEFAULT 0 NOT NULL,
    valid_rows          NUMBER DEFAULT 0 NOT NULL,
    rejected_rows       NUMBER DEFAULT 0 NOT NULL,
    created_by          VARCHAR2(100) DEFAULT USER NOT NULL,
    CONSTRAINT pk_etl_batch PRIMARY KEY (batch_id),
    CONSTRAINT ck_etl_batch_status CHECK (status IN ('RUNNING','SUCCESS','WARNING','FAILED'))
);

CREATE TABLE etl_log (
    log_id              NUMBER GENERATED BY DEFAULT AS IDENTITY,
    batch_id            NUMBER,
    log_level           VARCHAR2(20) DEFAULT 'INFO' NOT NULL,
    module_name         VARCHAR2(100),
    message             VARCHAR2(4000) NOT NULL,
    created_at          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_etl_log PRIMARY KEY (log_id),
    CONSTRAINT fk_etl_log_batch FOREIGN KEY (batch_id) REFERENCES etl_batch(batch_id),
    CONSTRAINT ck_etl_log_level CHECK (log_level IN ('DEBUG','INFO','WARNING','ERROR','FATAL'))
);

PROMPT Log tables created successfully.
