#!/usr/bin/env bash
set -euo pipefail

PROJECT_ROOT="${MINI_BOP_PROJECT_ROOT:-$(pwd)}"
cd "$PROJECT_ROOT"

echo "============================================================"
echo "MINI BOP - LOCAL RUNTIME ARTIFACT CLEANUP"
echo "============================================================"
echo "Project root: $PROJECT_ROOT"
echo ""

delete_path() {
  local target="$1"
  if [ -e "$target" ]; then
    echo "[DELETE] $target"
    rm -rf "$target"
  else
    echo "[SKIP]   $target"
  fi
}

# Runtime artifacts generated by Hive/Derby and local execution.
delete_path "metastore_db"
delete_path ".metastore_db"
delete_path "derby.log"
delete_path "spark-warehouse"
delete_path "warehouse"

# Python bytecode/cache artifacts.
find . -type d -name "__pycache__" -print -prune -exec rm -rf {} +
find . -type f \( -name "*.pyc" -o -name "*.pyo" \) -print -delete

# Temporary/log files generated during local runs.
find . -type f \( -name "*.tmp" -o -name "*.bak" -o -name "*.old" -o -name "*.orig" \) -print -delete

# Keep data/export and monitoring/reports because they are useful for demo and validation.
echo ""
echo "Cleanup completed."
echo "Run 'git status' to confirm removed runtime artifacts before committing."
echo "LOCAL_RUNTIME_CLEANUP_STATUS=COMPLETED"
