param(
    [string]$ProjectRoot = "F:\SSD_DEV\windows\projects\mini-bop"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

Write-Host "============================================================"
Write-Host "MINI BOP - LOCAL RUNTIME ARTIFACT CLEANUP"
Write-Host "============================================================"
Write-Host "Project root: $ProjectRoot"
Write-Host ""

Set-Location $ProjectRoot

function Remove-PathIfExists {
    param([string]$Path)
    if (Test-Path $Path) {
        Write-Host "[DELETE] $Path"
        Remove-Item -Recurse -Force $Path
    } else {
        Write-Host "[SKIP]   $Path"
    }
}

# Runtime artifacts generated by Hive/Derby and local execution.
Remove-PathIfExists "metastore_db"
Remove-PathIfExists ".metastore_db"
Remove-PathIfExists "derby.log"
Remove-PathIfExists "spark-warehouse"
Remove-PathIfExists "warehouse"

# Python bytecode/cache artifacts.
Get-ChildItem -Recurse -Force -Directory -Filter "__pycache__" | ForEach-Object {
    Write-Host "[DELETE] $($_.FullName)"
    Remove-Item -Recurse -Force $_.FullName
}

Get-ChildItem -Recurse -Force -File -Include "*.pyc","*.pyo","*.tmp","*.bak","*.old","*.orig" | ForEach-Object {
    Write-Host "[DELETE] $($_.FullName)"
    Remove-Item -Force $_.FullName
}

Write-Host ""
Write-Host "Cleanup completed."
Write-Host "Run 'git status' to confirm removed runtime artifacts before committing."
Write-Host "LOCAL_RUNTIME_CLEANUP_STATUS=COMPLETED"
